server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
#    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432/identity_service_demo}
#    driverClassName: "org.postgresql.Driver"
    url: ${DBMS_CONNECTION}
    driverClassName: ${DBMS_DRIVER}
    password: ${DBMS_PASSWORD}
    username: ${DBMS_USERNAME}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}

jwt:
  signerKey: ${JWT_SIGNERKEY}
  valid-duration: ${JWT_VALID_DURATION} # in second
  refreshable-duration: ${JWT_REFRESHABLE_DURATION} # in seconds
